apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prom-dpl
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
        # Prometheus Instance
        - name: prom
          image: prom/prometheus:v2.2.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prom-config
              mountPath: /etc/prometheus/
            - name: prom-data
              mountPath: /prometheus/
        # pg-adapter
        - name: prom-adp
          image: timescale/prometheus-postgresql-adapter:0.4.1
          imagePullPolicy: "IfNotPresent"
          args:
            - "-pg.host=pgts-svc"
            - "-pg.prometheus-log-samples"
            - "-pg.database=$(POSTGRES_DB)"
            - "-pg.user=$(POSTGRES_USER)"
            - "-pg.password=$(POSTGRES_PASSWORD)"
            - "-log.level=debug"
            - "-leader-election.pg-advisory-lock-id=1"
            - "-leader-election.pg-advisory-lock.prometheus-timeout=6s"
          ports:
            - containerPort: 9201
          envFrom:
            - configMapRef:
                name: pgts-cm
      volumes:
        # Volumes for First Prometheus
        - name: prom-config
          configMap:
            defaultMode: 420
            name: prom-cm
  
        - name: prom-data
          emptyDir: {}