apiVersion: v1
kind: Service
metadata:
  name: pg-prometheus
  namespace: monitoring
spec:
  selector: 
    app: pg-prometheus
  type: NodePort  
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432