apiVersion: v1
kind: Service
metadata:
  name: pg-prometheus
  namespace: monitoring
spec:
  selector: 
    app: pg-prometheus
  type: NodePort  
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pg-prometheus
  namespace: monitoring
  labels:
    type: local
    app: pg-prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /host_mnt/c/kube-data/pg-prometheus/pg-prometheus-db-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-prometheus
  namespace: monitoring
  labels:
    app: pg-prometheus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pg-prometheus
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pg-prometheus
    spec:
      containers:
        - name: pg-prometheus
          image: timescale/pg_prometheus:0.2.1
          imagePullPolicy: "IfNotPresent"
          args:
            - "postgres"
            - "-csynchronous_commit=off"
          envFrom:
            - configMapRef:
                name: pg-prometheus
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pg-prometheus-db
              mountPath: /var/lib/postgresql/data/
      volumes:
        - name: pg-prometheus-db
          persistentVolumeClaim:
            claimName: pg-prometheus