kind: PersistentVolume
apiVersion: v1
metadata:
  name: pg-prometheus
  namespace: monitoring
  labels:
    type: local
    app: pg-prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /host_mnt/c/kube-data/pg-prometheus/pg-prometheus-db-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-prometheus
  namespace: monitoring
  labels:
    app: pg-prometheus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi