apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-prometheus
  namespace: monitoring
  labels:
    app: pg-prometheus
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
  #PDDATA: /var/lib/postgresql/data/