apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        # Prometheus Instance
        - name: prometheus
          image: prom/prometheus:v2.2.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
            - name: prometheus-storage
              mountPath: /prometheus/
        # pg-adapter
        - name: prometheus-pg-adapter
          image: timescale/prometheus-postgresql-adapter:0.4.1
          imagePullPolicy: "IfNotPresent"
          args:
            - "-pg.host=pg-prometheus"
            - "-pg.prometheus-log-samples"
            - "-log.level=debug"
            - "-leader-election.pg-advisory-lock-id=1"
            - "-leader-election.pg-advisory-lock.prometheus-timeout=6s"
          ports:
            - containerPort: 9201
      volumes:
        # Volumes for First Prometheus
        - name: prometheus-config
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
  
        - name: prometheus-storage
          emptyDir: {}