apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-pg-adapter-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-pg-adapter
    spec:
      containers:
        - name: prometheus1-pg-adapter
          image: timescale/prometheus-postgresql-adapter:0.4.1
          imagePullPolicy: "IfNotPresent"
          args:
            - "-pg.host=pg-prometheus-deployment"
            - "-pg.prometheus-log-samples"
            - "-log.level=debug"
            - "-leader-election.pg-advisory-lock-id=1"
            - "-leader-election.pg-advisory-lock.prometheus-timeout=6s"
          ports:
            - containerPort: 9201
            
        - name: prometheus2-pg-adapter
          image: timescale/prometheus-postgresql-adapter:0.4.1
          imagePullPolicy: "IfNotPresent"
          args:
            - "-pg.host=pg-prometheus-deployment"
            - "-pg.prometheus-log-samples"
            - "-log.level=debug"
            - "-web.listen-address=:9202"
            - "-leader-election.pg-advisory-lock-id=1"
            - "-leader-election.pg-advisory-lock.prometheus-timeout=6s"
          ports:
            - containerPort: 9202