kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgts-pv
  labels:
    type: local
    app: pgts
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kube/pgts/pgts-pv/