kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgts-pvc
  labels:
    app: pgts
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi